[package]
name = "redox_installer"
version = "0.2.2"
description = "A Redox filesystem builder"
license = "MIT"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
repository = "https://gitlab.redox-os.org/redox-os/installer"

[[bin]]
name = "redox_installer"
path = "src/bin/installer.rs"

[lib]
name = "redox_installer"
path = "src/lib.rs"

[dependencies]
arg_parser = "0.1"
argon2rs = { version = "0.2", default-features = false }
liner = "0.1"
libc = "0.2"
failure = "0.1"
rand = "0.3"
redox_pkgutils = "0.1"
redoxfs = "0.3"
serde = "0.8"
serde_derive = "0.8"
termion = "1.5.1"
toml = { version = "0.2", default-features = false, features = ["serde"] }
