[package]
name = "redox_installer"
version = "0.2.0"

[[bin]]
name = "redox_installer"
path = "src/bin/installer.rs"

[lib]
name = "redox_installer"
path = "src/lib.rs"

[dependencies]
arg_parser = { git = "https://gitlab.redox-os.org/redox-os/arg-parser.git" }
argon2rs = { version = "0.2", default-features = false }
liner = "0.1"
libc = { git = "https://gitlab.redox-os.org/redox-os/liblibc.git", branch = "redox" }
failure = "0.1"
pkgutils = { git = "https://gitlab.redox-os.org/redox-os/pkgutils.git" }
rand = "0.3"
redoxfs = "0.3"
serde = "0.8"
serde_derive = "0.8"
termion = "1.5.1"
toml = { version = "0.2", default-features = false, features = ["serde"] }
