[package]
name = "redox_installer"
version = "0.2.0"

[[bin]]
name = "redox_installer"
path = "src/bin/installer.rs"

[lib]
name = "redox_installer"
path = "src/lib.rs"

[dependencies]
arg_parser = { git = "https://github.com/redox-os/arg-parser.git" }
liner = "0.1"
pkgutils = { git = "https://github.com/redox-os/pkgutils.git" }
rand = "0.3"
redoxfs = "0.3"
serde = "0.8"
serde_derive = "0.8"
termion = "1.5.1"
toml = { version = "0.2", default-features = false, features = ["serde"] }
redox_users = { git = "https://github.com/redox-os/users.git" }
