# This is the default configuration file

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
acid = {}
coreutils = {}
extrautils = {}
games = {}
ion = {}
netutils = {}
pkgutils = {}
orbutils = {}
smith = {}
userutils = {}

# User settings
[users.root]
# Password is set to "password"
password = "$argon2i$m=4096,t=10,p=1$Tnc4UVV0N00$ML9LIOujd3nmAfkAwEcSTMPqakWUF0OUiLWrIy0nGLk"
uid = 0
gid = 0
name = "root"
home = "/root"

[users.user]
# Password is unset
password = ""
