# This is an example configuration file

# General settings
[general]
# Prompt if settings are not defined
prompt = true

# Package settings
[packages]
acid = {}
binutils = {}
coreutils = {}
extrautils = {}
games = {}
ion = {}
netutils = {}
orbdata = {}
orbital = {}
orbutils = {}
pkgutils = {}
smith = {}
userutils = {}

# User settings
[users.root]
uid = 0
gid = 0
home = "/root"

[users.user]
